// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actor_position.proto

#include "actor_position.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR ActorPosition::ActorPosition(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.position_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ActorPositionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActorPositionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActorPositionDefaultTypeInternal() {}
  union {
    ActorPosition _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActorPositionDefaultTypeInternal _ActorPosition_default_instance_;
static ::_pb::Metadata file_level_metadata_actor_5fposition_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_actor_5fposition_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_actor_5fposition_2eproto = nullptr;

const uint32_t TableStruct_actor_5fposition_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ActorPosition, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ActorPosition, _impl_.position_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ActorPosition)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_ActorPosition_default_instance_._instance,
};

const char descriptor_table_protodef_actor_5fposition_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024actor_position.proto\032\014vector.proto\"(\n\r"
  "ActorPosition\022\027\n\010position\030\001 \001(\0132\005.Vec3b\006"
  "proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_actor_5fposition_2eproto_deps[1] = {
  &::descriptor_table_vector_2eproto,
};
static ::_pbi::once_flag descriptor_table_actor_5fposition_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_actor_5fposition_2eproto = {
    false, false, 86, descriptor_table_protodef_actor_5fposition_2eproto,
    "actor_position.proto",
    &descriptor_table_actor_5fposition_2eproto_once, descriptor_table_actor_5fposition_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_actor_5fposition_2eproto::offsets,
    file_level_metadata_actor_5fposition_2eproto, file_level_enum_descriptors_actor_5fposition_2eproto,
    file_level_service_descriptors_actor_5fposition_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_actor_5fposition_2eproto_getter() {
  return &descriptor_table_actor_5fposition_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_actor_5fposition_2eproto(&descriptor_table_actor_5fposition_2eproto);

// ===================================================================

class ActorPosition::_Internal {
 public:
  static const ::Vec3& position(const ActorPosition* msg);
};

const ::Vec3&
ActorPosition::_Internal::position(const ActorPosition* msg) {
  return *msg->_impl_.position_;
}
void ActorPosition::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
ActorPosition::ActorPosition(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ActorPosition)
}
ActorPosition::ActorPosition(const ActorPosition& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ActorPosition* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_position()) {
    _this->_impl_.position_ = new ::Vec3(*from._impl_.position_);
  }
  // @@protoc_insertion_point(copy_constructor:ActorPosition)
}

inline void ActorPosition::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ActorPosition::~ActorPosition() {
  // @@protoc_insertion_point(destructor:ActorPosition)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ActorPosition::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.position_;
}

void ActorPosition::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ActorPosition::Clear() {
// @@protoc_insertion_point(message_clear_start:ActorPosition)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActorPosition::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Vec3 position = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ActorPosition::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ActorPosition)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Vec3 position = 1;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ActorPosition)
  return target;
}

size_t ActorPosition::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ActorPosition)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Vec3 position = 1;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.position_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ActorPosition::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ActorPosition::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ActorPosition::GetClassData() const { return &_class_data_; }


void ActorPosition::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ActorPosition*>(&to_msg);
  auto& from = static_cast<const ActorPosition&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ActorPosition)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_position()) {
    _this->_internal_mutable_position()->::Vec3::MergeFrom(
        from._internal_position());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ActorPosition::CopyFrom(const ActorPosition& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ActorPosition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActorPosition::IsInitialized() const {
  return true;
}

void ActorPosition::InternalSwap(ActorPosition* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.position_, other->_impl_.position_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ActorPosition::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_actor_5fposition_2eproto_getter, &descriptor_table_actor_5fposition_2eproto_once,
      file_level_metadata_actor_5fposition_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ActorPosition*
Arena::CreateMaybeMessage< ::ActorPosition >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ActorPosition >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
