// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movement.proto

#include "movement.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR Movement::Movement(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.progess_vector_)*/nullptr
  , /*decltype(_impl_.forward_vector_)*/nullptr
  , /*decltype(_impl_.right_vector_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MovementDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MovementDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MovementDefaultTypeInternal() {}
  union {
    Movement _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MovementDefaultTypeInternal _Movement_default_instance_;
static ::_pb::Metadata file_level_metadata_movement_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_movement_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_movement_2eproto = nullptr;

const uint32_t TableStruct_movement_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Movement, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Movement, _impl_.progess_vector_),
  PROTOBUF_FIELD_OFFSET(::Movement, _impl_.forward_vector_),
  PROTOBUF_FIELD_OFFSET(::Movement, _impl_.right_vector_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Movement)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_Movement_default_instance_._instance,
};

const char descriptor_table_protodef_movement_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016movement.proto\032\014vector.proto\"e\n\010Moveme"
  "nt\022\035\n\016progess_vector\030\001 \001(\0132\005.Vec3\022\035\n\016for"
  "ward_vector\030\002 \001(\0132\005.Vec3\022\033\n\014right_vector"
  "\030\003 \001(\0132\005.Vec3b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_movement_2eproto_deps[1] = {
  &::descriptor_table_vector_2eproto,
};
static ::_pbi::once_flag descriptor_table_movement_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_movement_2eproto = {
    false, false, 141, descriptor_table_protodef_movement_2eproto,
    "movement.proto",
    &descriptor_table_movement_2eproto_once, descriptor_table_movement_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_movement_2eproto::offsets,
    file_level_metadata_movement_2eproto, file_level_enum_descriptors_movement_2eproto,
    file_level_service_descriptors_movement_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_movement_2eproto_getter() {
  return &descriptor_table_movement_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_movement_2eproto(&descriptor_table_movement_2eproto);

// ===================================================================

class Movement::_Internal {
 public:
  static const ::Vec3& progess_vector(const Movement* msg);
  static const ::Vec3& forward_vector(const Movement* msg);
  static const ::Vec3& right_vector(const Movement* msg);
};

const ::Vec3&
Movement::_Internal::progess_vector(const Movement* msg) {
  return *msg->_impl_.progess_vector_;
}
const ::Vec3&
Movement::_Internal::forward_vector(const Movement* msg) {
  return *msg->_impl_.forward_vector_;
}
const ::Vec3&
Movement::_Internal::right_vector(const Movement* msg) {
  return *msg->_impl_.right_vector_;
}
void Movement::clear_progess_vector() {
  if (GetArenaForAllocation() == nullptr && _impl_.progess_vector_ != nullptr) {
    delete _impl_.progess_vector_;
  }
  _impl_.progess_vector_ = nullptr;
}
void Movement::clear_forward_vector() {
  if (GetArenaForAllocation() == nullptr && _impl_.forward_vector_ != nullptr) {
    delete _impl_.forward_vector_;
  }
  _impl_.forward_vector_ = nullptr;
}
void Movement::clear_right_vector() {
  if (GetArenaForAllocation() == nullptr && _impl_.right_vector_ != nullptr) {
    delete _impl_.right_vector_;
  }
  _impl_.right_vector_ = nullptr;
}
Movement::Movement(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Movement)
}
Movement::Movement(const Movement& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Movement* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.progess_vector_){nullptr}
    , decltype(_impl_.forward_vector_){nullptr}
    , decltype(_impl_.right_vector_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_progess_vector()) {
    _this->_impl_.progess_vector_ = new ::Vec3(*from._impl_.progess_vector_);
  }
  if (from._internal_has_forward_vector()) {
    _this->_impl_.forward_vector_ = new ::Vec3(*from._impl_.forward_vector_);
  }
  if (from._internal_has_right_vector()) {
    _this->_impl_.right_vector_ = new ::Vec3(*from._impl_.right_vector_);
  }
  // @@protoc_insertion_point(copy_constructor:Movement)
}

inline void Movement::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.progess_vector_){nullptr}
    , decltype(_impl_.forward_vector_){nullptr}
    , decltype(_impl_.right_vector_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Movement::~Movement() {
  // @@protoc_insertion_point(destructor:Movement)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Movement::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.progess_vector_;
  if (this != internal_default_instance()) delete _impl_.forward_vector_;
  if (this != internal_default_instance()) delete _impl_.right_vector_;
}

void Movement::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Movement::Clear() {
// @@protoc_insertion_point(message_clear_start:Movement)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.progess_vector_ != nullptr) {
    delete _impl_.progess_vector_;
  }
  _impl_.progess_vector_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.forward_vector_ != nullptr) {
    delete _impl_.forward_vector_;
  }
  _impl_.forward_vector_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.right_vector_ != nullptr) {
    delete _impl_.right_vector_;
  }
  _impl_.right_vector_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Movement::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Vec3 progess_vector = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_progess_vector(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Vec3 forward_vector = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_forward_vector(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Vec3 right_vector = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_right_vector(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Movement::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Movement)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Vec3 progess_vector = 1;
  if (this->_internal_has_progess_vector()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::progess_vector(this),
        _Internal::progess_vector(this).GetCachedSize(), target, stream);
  }

  // .Vec3 forward_vector = 2;
  if (this->_internal_has_forward_vector()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::forward_vector(this),
        _Internal::forward_vector(this).GetCachedSize(), target, stream);
  }

  // .Vec3 right_vector = 3;
  if (this->_internal_has_right_vector()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::right_vector(this),
        _Internal::right_vector(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Movement)
  return target;
}

size_t Movement::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Movement)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Vec3 progess_vector = 1;
  if (this->_internal_has_progess_vector()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.progess_vector_);
  }

  // .Vec3 forward_vector = 2;
  if (this->_internal_has_forward_vector()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.forward_vector_);
  }

  // .Vec3 right_vector = 3;
  if (this->_internal_has_right_vector()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.right_vector_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Movement::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Movement::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Movement::GetClassData() const { return &_class_data_; }


void Movement::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Movement*>(&to_msg);
  auto& from = static_cast<const Movement&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Movement)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_progess_vector()) {
    _this->_internal_mutable_progess_vector()->::Vec3::MergeFrom(
        from._internal_progess_vector());
  }
  if (from._internal_has_forward_vector()) {
    _this->_internal_mutable_forward_vector()->::Vec3::MergeFrom(
        from._internal_forward_vector());
  }
  if (from._internal_has_right_vector()) {
    _this->_internal_mutable_right_vector()->::Vec3::MergeFrom(
        from._internal_right_vector());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Movement::CopyFrom(const Movement& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Movement)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Movement::IsInitialized() const {
  return true;
}

void Movement::InternalSwap(Movement* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Movement, _impl_.right_vector_)
      + sizeof(Movement::_impl_.right_vector_)
      - PROTOBUF_FIELD_OFFSET(Movement, _impl_.progess_vector_)>(
          reinterpret_cast<char*>(&_impl_.progess_vector_),
          reinterpret_cast<char*>(&other->_impl_.progess_vector_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Movement::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_movement_2eproto_getter, &descriptor_table_movement_2eproto_once,
      file_level_metadata_movement_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Movement*
Arena::CreateMaybeMessage< ::Movement >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Movement >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
